# Generated by Django 6.0.2 on 2026-02-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_grade_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
